-- =============================================================================
-- Seed de desenvolvimento local — A REESCREVER
-- =============================================================================
-- O seed anterior criava os dados chamando as MESMAS RPCs que a aplicação usa
-- (`iniciar_bateria`, `finalizar_bateria`, …), de propósito: assim ele validava
-- o contrato das RPCs a cada `db reset` em vez de inserir por dentro e mascarar
-- regressão de regra.
--
-- Essas RPCs não existem neste schema. A migration inicial da reimplementação
-- traz estrutura e proteções; a execução de bateria vai ser redesenhada, e o
-- seed volta junto com ela — pelo mesmo princípio, não por INSERT direto.
--
-- O arquivo antigo continua no histórico:
--
--   git show 8569f1a:supabase/seed.sql
--
-- Enquanto isso, `npm run db:reset` sobe o banco vazio, que é o suficiente para
-- aplicar e inspecionar o schema.
-- =============================================================================
